project: 
  type: book
  output-dir: _book
  
book:
  title: "PSD Whale Ecology Branch Lab Manual"
  author: "Danielle Cholewiak & WEB members"
  date: last-modified 
  description: "This is the branch manual for the WEB Lab at the NEFSC" 
  
  page-footer:
    left: |
      <a href="https://www.fisheries.noaa.gov/new-england-mid-atlantic/about-us/protected-species-research-northeast">The Protected Species Division</a>
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  site-url: https://dcholewiak1.github.io/WEB-lab-manual/
  repo-url: https://dcholewiak1.github.io/WEB-lab-manual/
  repo-actions: [edit,issue]

  chapters: 
    - index.qmd
    - 01-intro-how-we-work.qmd
 #   - 03-code-of-conduct.qmd
    - 04-onboarding.qmd
    - 05-expectations-communication.qmd
    - 07-small_boat_work.qmd
    - 08-aerial_surveys.qmd
    - 09-mortality_serious_injury.qmd
    - 10-population-ecological-modeling.qmd
    - 11-GAIA.qmd
    - CEB.qmd
    - 12-Publications.qmd
    - 13-nefsc-resources.qmd
    
    - 20-offboarding.qmd
    
    
#    - 09-communication.qmd
#   - 02-lab-culture-philosophy.qmd
#    - 13-smast-resources.qmd
#    - 14-other-faylab-resources.qmd  


# not sure what the following line does; those files are present
bibliography: [references.bib, book.bib]

